sudo: false
language: go
go:
  - 1.5.3
  - 1.6.2
  - tip
env:
  global:
    - GO15VENDOREXPERIMENT=1
  matrix:
    - ES_VERSION=2.3.2
  allow_failures:
    - go: tip
before_script:
  - mkdir ${HOME}/elasticsearch
  - wget http://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/${ES_VERSION}/elasticsearch-${ES_VERSION}.tar.gz
  - tar -xzvf elasticsearch-${ES_VERSION}.tar.gz -C ${HOME}/elasticsearch
  - ls -alFR ${HOME}/elasticsearch
  - cp config/elasticsearch.yml ${HOME}/elasticsearch/elasticsearch-${ES_VERSION}/config/
  - cat ${HOME}/elasticsearch/elasticsearch-${ES_VERSION}/config/elasticsearch.yml
  - ${HOME}/elasticsearch/elasticsearch-${ES_VERSION}/bin/elasticsearch >& /dev/null &
  - sleep 15
