on:
  push:
    branches:
      - '*.v2'
  pull_request:
    branches:
      - '*.v2'
name: Test
jobs:
  test:
    strategy:
      matrix:
        go: [1.20.x]
        os: [ubuntu-latest]
    name: Run ${{ matrix.go }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Prepare tests
      run: |
        sudo apt-get install -y netcat
        sudo sysctl -w vm.max_map_count=262144

    - name: Setup Go ${{ matrix.go }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Checkout code
      uses: actions/checkout@v4

    #- uses: actions/cache@v4
    #  with:
    #    path: |
    #      ~/.cache/go-build
    #      ~/go/pkg/mod
    #    key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    #    restore-keys: |
    #      ${{ runner.os }}-go-

    - name: Run Docker containers
      run: docker-compose up -d

    - name: Check Docker containers
      run: docker ps -a

    #- name: Get dependencies
    #  run: |
    #    go get -u github.com/google/go-cmp/cmp
    #    go get -u github.com/fortytw2/leaktest
    #    go mod tidy

    - name: Wait for Opensearch
      run: |
        while ! nc -z localhost 9200; do sleep 1; done
        sleep 60

    - name: Run the tests
      run: |
        go test -covermode=atomic -coverprofile cover.out -deprecations -strict-decoder -v . ./config/... ./trace/... ./uritemplates/...

    - uses: codecov/codecov-action@v3
      with:
        files: coverage.txt
        flags: unittests
        fail_ci_if_error: true